# Generated by Django 2.1 on 2018-11-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_user_tables_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_tables',
            name='user_type',
            field=models.IntegerField(null=True),
        ),
    ]
